---
# Configuration for Better Code analysis.
# See https://bettercodehub.com/docs/configuration-manual
exclude:
    - /bin/.*
    - /tasks/.*
    - /tests/.*
    - /third_party/.*
    - /tools/.*
# Set component depth to match //programl/<component> structure.
component_depth: 2
