# Configuration for Better Code analysis.
# See https://bettercodehub.com/docs/configuration-manual
exclude:
  - /third_party/.*
# Set component depth to match //programl/<component> structure.
component_depth: 2
